### ISSUE TITLE
can't use n during tutorial while typing in text areas

### ISSUE THREAD

**Issue by wisec** [hhvm/hacklang.org#15]
If you try to fix an issue in the tutorial, 
and type a 'n' character in the textarea, you'll be taken to the (N)ext excercise...

**Comment by JoelMarcey** [comment]
@wisec What browser and OS are you using?

**Comment by wisec** [comment]
Chrome on Linux,
it does not seem to happen every time, seems related to some element focusing status, 
I'll reopen it if it happens again and I have a reproducing example.
Thanks!
