### ISSUE TITLE
Tooltip background issue in the tutorial in Firefox

### ISSUE THREAD

**Issue by clarkwinkelmann** [hhvm/hacklang.org#2]
Hi there !

I just discovered this Hack thing and noticed a problem with the tutorial at <http://hacklang.org/tutorial.html>

In Firefox, the background of the tooltip is light grey, so I cannot read the text :(

![hacklangtutorialtooltipbackgroundfirefox](https://cloud.githubusercontent.com/assets/5264300/21446087/044dc840-c8c2-11e6-8e48-8b862e26e36f.png)

That's Firefox 50.1 on Ubuntu. The popup is fine in Chrome on the same PC.

The culprit seems to be the `background-color: infobackground;` for the `.CodeMirror-lint-tooltip` class. Is that some new CSS variable not yet supported by Firefox ?

**Comment by JoelMarcey** [comment]
Interesting. Firefox 50.1.0 on a Mac seems ok.

<img width="1152" alt="screenshot 2016-12-27 14 16 38" src="https://cloud.githubusercontent.com/assets/3757713/21509569/2196bc92-cc3f-11e6-8ad1-19c064482f7a.png">

So this could be an Ubuntu/Firefox thing as opposed to FireFox overall.

**Comment by clarkwinkelmann** [comment]
I did some more testing. I didn't know about that `InfoBackground` CSS color.

Windows is OK (yellow as well).

Problem persists with bare Ubuntu 16.04.1 installation with or without the Ubuntu Additions addon.

On Ubuntu it seems to return the following (found with inspection tools):

- `InfoBackground` is `#F2F1F0`
- `InfoText` is `#FFFFFF`

On Xubuntu it is working as expected, the popup has the colors of the system tooltip, black:

![hacklangtutorialtooltipbackgroundfirefoxxubuntu501](https://cloud.githubusercontent.com/assets/5264300/21570399/045329ac-cec6-11e6-8d0c-934cc1491677.png)

The rule is in [this file](https://github.com/hhvm/hacklang.org/blob/master/js/hack_tutorial/codemirror/addon/lint/lint.css#L7). I believe this comes from https://github.com/codemirror/CodeMirror ?

It looks like they have gone back to using basic CSS colors in [their version](https://github.com/codemirror/CodeMirror/blob/master/addon/lint/lint.css). Maybe do an update ?

Edit: it was reported there on their side: https://github.com/codemirror/CodeMirror/issues/4025

**Comment by JoelMarcey** [comment]
@clarkwinkelmann Thanks for the information. Is this something you might be willing to submit a pull request for?

**Comment by clarkwinkelmann** [comment]
It seems the tutorial is using version 3.2 of the CodeMirror library (seen here <https://github.com/hhvm/hacklang.org/blob/master/js/hack_tutorial/codemirror/lib/codemirror.js#L1>)

The fix requires to update to at least version 5.15 <https://github.com/codemirror/CodeMirror/blob/5.15.0/addon/lint/lint.css>

The major version bump requires to check for compatibility, and I have no idea how it was coded (would require spending some time on the tutorial JS code). It would be quicker if the person who originally coded it had a look for compatibility issues :grimacing: Additionally, I have no idea how that CodeMirror library works...

Or, I could submit a PR where I only patch the css file with the latest version (only these two lines changed) but this may cause problems (or be erased) if the library is updated in the future (to v4 for example) !

**Comment by JoelMarcey** [comment]
I don't think we have plans on updating the CodeMirror library in the near-term. So maybe a short-term fix would be just fine. So I would submit the simplest PR as possible that fixes your issue (and doesn't break other browsers, of course :) ), assuming the CodeMirror library stays the same.
