### ISSUE TITLE
There is nothing on the front page, that says what Hack even is or what its point and purpose is.

### ISSUE THREAD

**Issue by navid-zamani** [hhvm/hacklang.org#35]
No, I’m not gonna waste time watching a video for info that takes literally 5 seconds of quick scanning/glancing at my own pace if it was text. I’m not 12. Is this a joke?

Be happy I showed you the courtesy of reporting this bug at all, instead of mentally marking Hack as junk to avoid and closing the tab.

**Comment by Wilfred** [comment]
Thanks for your feedback. We do have the core Hack features on the homepage, and you can visit https://docs.hhvm.com/ to get in-depth details.
