### ISSUE TITLE
Force HTTPS 🔒

### ISSUE THREAD

**Issue by theel0ja** [hhvm/hacklang.org#6]
The site is accessible using HTTPS ([https://hacklang.org/](https://hacklang.org)).

https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

Also the url parameter (see below) should be changed.

https://github.com/hhvm/hacklang.org/blob/33a81c47eb5904c04031f20ce013ea745945f676/_config.yml#L19

**Comment by JoelMarcey** [comment]
HTTPS is forced now.
